################################################################################
################################################################################
#########                                                             ##########
#########               GeneRaMeN UI for tutorials tab                ##########
#########                                                             ##########
################################################################################
################################################################################

tabPanel("Tutorial",
         
         # CSS script for enabling separate scroll bar for each side of line
         tags$style(
           HTML(".scrollable-column {
           height: 850px;
           overflow-y: auto;
                }")
         ),
         
         # CSS script to put a line in between the two main sections (columns)
         # tags$head(
         #   tags$style(
         #     HTML(".divider-line {
         #     border-right: 1px solid #ccc;
         #     height: 100%;
         #     margin-right: 1px;
         #          }")
         #   )
         # ),
         # 
         fluidRow(
           
           # Rank aggregation tutorial column
           column(4,
                  fluidRow(
                    column(12,
                           class = "scrollable-column",
                           h1(strong("1. Rank Aggregation Analysis")),
                           h3(strong("1.1 Inputs")),
                           p(strong("1.1.1 Selecting datasets:")),
                           p("If the users wish to use any of the pre-loaded screening datasets as demo, they can just click on the button next to the dataset name.", 
                             "If they wish to upload and analyze their own dataset, they can select 'None' and proceed to the next section, “Uploading your own dataset”."),
                             "\n •	Please note that in case you do select a pre-loaded dataset and proceed to upload your data as well, GeneRaMeN would assume that you want to append your data to the pre-loaded one and will combine both datasets.",
                           br(),
                           tags$img(src = "Asset 2.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.1.2 Uploading your own dataset:")),
                           p("GeneRaMeN allows the user to upload one excel file (.xls or .xlsx) for the input ranked gene list, which can contain any number of sheets.",
                             "Each sheet then corresponds to a separate ranked gene list that you want to be included in the analysis.", 
                             "There is no limitation on the format of these gene lists as long as the first column corresponds to the “Gene names” or “Gene symbols” (Thus, Gene summary output from MAGeCK can readily be pasted into the excel sheet and used by GeneRaMeN).",
                             "Please note that this list must already be SORTED.",
                             "Since GeneRaMeN reads the first column as gene rankings it is agnostic to whether your current ranking is correctly sorted or not, therefore it is on the user to make sure all hit lists are correctly sorted.",
                             "To download an example of input file template accepted by GeneRaMeN please click",
                             a("here.", href = "https://github.com/MeisamYSF/GeneRaMeN/raw/main/SampleDataFile_GeneRaMeN.xlsx")),
                           "\n •	Please note that GeneRaMeN currently accepts Human gene lists only, since all gene lists undergo standardization to their latest HGNC official gene name.",
                           br(),
                           tags$img(src = "Asset 3.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.1.3 Including meta-data:")),
                           p("Additional information (e.g., cell lines, disease phenotype, etc.) can be supplemented to the studies included in the analysis.",
                             "Some meta-data such as cell lines and screening methods are already included for the pre-loaded datasets, but in case the users have opted to upload their own datasets and want to visualize heatmaps with meta-data, they must upload a meta-data file that is compatible with the uploaded dataset (same number of studies, and with same study names).",
                             "To download an example of meta-data file template acceptable by GeneRaMeN please click",
                             a("here.", href = "https://github.com/MeisamYSF/GeneRaMeN/raw/main/SampleMetaDataFile_GeneRaMeN.xlsx")),
                           "\n •	Note that this step is optional and for visualization purposes only (see “output” section in the following), thus has no impact on the analysis outcome.",
                           br(),
                           tags$img(src = "Asset 4.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.1.4 Rank aggregation settings and submission:")),
                           p("Once the input datasets are selected, the user needs to determine which rank aggregation method they want to use, with Robust rank aggregation (RRA) selected as default.",
                             "It is strongly recommended to put a maximum rank cut-off in the analysis to ensure all rankings have biological meanings.",
                             "However, if the user does not want to put such a threshold, they can set it to the total number of genes, keeping all the original ranks.",
                             "The default value is set to 5000. When all fields are filled press the submit button to run rank aggregation on your data."),
                             "\n •	Note that regardless of the maximum rank value, all genes are going to be included for the analysis.",
                             "The maximum rank cut-off is to determine that genes ranking beyond the certain value would be treated as all having that same maximum rank.",
                           br(),
                           tags$img(src = "Asset 5.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           h3(strong("1.2 Outputs")),
                           p(strong("1.2.1 Input overview:")),
                           p("Once the input data is selected/uploaded by the user, they can readily see an overview of the studies in a table format on the main panel.",
                           "If meta-data is included, that information would also be displayed for each study."),
                           br(),
                           tags$img(src = "Asset 6.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.2.2 Aggregated ranks list:")),
                           p("Upon submitting the lists, the user is automatically guided to the “Aggregated ranks” tab, in which the results of the rank aggregation are shown.",
                           "The data table includes gene names, the aggregated ranks and scores calculated by the method of choice, as well as links for each gene’s pages on popular databases.",
                           "The aggregated rank for any gene of interest can be searched through the search box.",
                           "The entire table can be downloaded in csv format by clicking on the “Download table!” button."),
                           br(),
                           tags$img(src = "Asset 7.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.2.3 Scatter plot visualization of aggregated ranks:")),
                           p("Genetic screening results are often visualized via scatter plots in which the y axis corresponds to the enrichment/significance scores.",
                           "GeneRaMeN automatically generates a scatter plot for the aggregated ranks list which can be accessed under the “Scatter plot” tab.",
                           "The number of top genes to be highlighted/labeled can be fine-tuned by the bar on the top.",
                           "Plots can be downloaded in desired sizes and formats (PNG, PDF, and JPEG) from the download panel at the bottom."),
                           br(),
                           tags$img(src = "Asset 8.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.2.4 Gene rank finder:")),
                           p("This data table includes the original rankings of each gene across all datasets, and can be searched for genes of interest via the search box."),
                           br(),
                           tags$img(src = "Asset 9.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.2.5 Heatmap showing the original ranks of top aggregated genes:")),
                           p("The original rankings of the top aggregated genes can also be visualized in heatmaps.",
                           "The studies would undergo clustering as well to identify which studies are more similar to each other, regarding the ranks of the top aggregated genes.",
                           "If meta-data are included, they’d be shown as annotation bars on the top of the heatmap.",
                           "The number of top genes to be included can be fine-tuned by the scale bar at the top.",
                           "Plots can be downloaded in desired sizes and formats (PNG, PDF, and JPEG) from the download panel at the bottom."),
                           br(),
                           tags$img(src = "Asset 10.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("1.2.6 Gene ontology and pathway enrichment analysis of top aggregated genes:")),
                           p("The user can select the number of top aggregated genes to be included in the gene ontology or enrichment analysis.",
                           "Upon submission, GeneRaMeN sends these genes as queries to the g:profiler database to perform gene ontology (Biological process, Molecular function, Cellular compartment) and KEGG pathway enrichment analysis.",
                           "P-value threshold of the overrepresentation analysis can be adjusted by user to filter results based on their desired statistical significance.",
                           "Results would be shown in data tables containing term name, size, and enrichment p-values, as well as a list of enriched genes associated with each term.",
                           "The entire table can be downloaded in csv format by clicking on the “Download table!” button on top.",
                           "The enrichment results are also automatically displayed as bubble plots, which can be downloaded in desired sizes and formats (PNG, PDF, and JPEG) from the download panel at the bottom."),
                           br(),
                           tags$img(src = "Asset 11.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                    ),
                    
                    ### vertical line
                    # column(
                    #   1,
                    #   div(class = "divider-line")
                    # ),
                  )),
           
           # Rank uniqueness tutorial column
           column(4,
                  class = "scrollable-column",
                  h1(strong("2. Rank Uniqueness Analysis")),
                  h3(strong("2.1 Inputs")),
                  p(strong("2.1.1 Selecting datasets:")),
                  p("If the users wish to use any of the pre-loaded screening datasets as demo, they can just click on the button next to the dataset name.", 
                    "If they wish to upload and analyze their own dataset, they can select 'None' and proceed to the next section, “Uploading your own dataset”."),
                    "\n •	Please note that in case you do select a pre-loaded dataset and proceed to upload your data as well, GeneRaMeN would assume that you want to append your data to the pre-loaded one and will combine both datasets.",
                  br(),
                  tags$img(src = "Asset 2.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
                  p(strong("2.1.2 Uploading your own dataset:")),
                  p("GeneRaMeN allows the user to upload one excel file (.xls or .xlsx) for the input ranked gene list, which can contain any number of sheets.",
                    "Each sheet then corresponds to a separate ranked gene list that you want to be included in the analysis.", 
                    "There is no limitation on the format of these gene lists as long as the first column corresponds to the “Gene names” or “Gene symbols” (Thus, Gene summary output from MAGeCK can readily be pasted into the excel sheet and used by GeneRaMeN).",
                    "Please note that this list must already be SORTED.",
                    "Since GeneRaMeN reads the first column as gene rankings it is agnostic to whether your current ranking is correctly sorted or not, therefore it is on the user to make sure all hit lists are correctly sorted.",
                    "To download an example of input file template accepted by GeneRaMeN please click",
                    a("here.", href = "https://github.com/MeisamYSF/GeneRaMeN/raw/main/SampleDataFile_GeneRaMeN.xlsx")),
                  "\n •	Please note that GeneRaMeN currently accepts Human gene lists only, since all gene lists undergo standardization to their latest HGNC official gene name.",
                  br(),
                  tags$img(src = "Asset 3.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
                  p(strong("2.1.3 Including meta-data:")),
                  p("Additional information (e.g., cell lines, disease phenotype, etc.) can be supplemented to the studies included in the analysis.",
                    "Some meta-data such as cell lines and screening methods are already included for the pre-loaded datasets, but in case the users have opted to upload their own datasets and want to visualize heatmaps with meta-data, they must upload a meta-data file that is compatible with the uploaded dataset (same number of studies, and with same study names).",
                    "To download an example of meta-data file template acceptable by GeneRaMeN please click",
                    a("here.", href = "https://github.com/MeisamYSF/GeneRaMeN/raw/main/SampleMetaDataFile_GeneRaMeN.xlsx")),
                  "\n •	Note that this step is optional and for visualization purposes only (see “output” section in the following), thus has no impact on the analysis outcome.",
                  br(),
                  tags$img(src = "Asset 4.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
                  p(strong("2.1.4 Contrast panel:")),
                  p("Upon selection/upload of the dataset, GeneRaMeN prompts the user to divide the studies in two groups to be analyzed for uniqueness markers.",
                  "To select a study just click on its name in the widget.",
                  "At least one study needs to be selected."),
                  br(),
                  tags$img(src = "Asset 13.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
                  p(strong("2.1.5  Rank uniqueness settings and submission:")),
                  p("Once the groups are assigned, the users need to determine the rank uniqueness analysis method they wish to use.",
                    "Multiple one-way t-tests are default method, but users may opt for parallel rank aggregations using any of the rank aggregation methods as described in the “Rank aggregation” section.",
                    "It is strongly recommended to put a maximum rank cut-off in the analysis to ensure all rankings have biological meanings.",
                    "However, if the user does not want to put such a threshold, they can set it to the total number of genes, keeping all the original ranks.",
                    "The default value is set to 5000. When all fields are filled press the submit button to run rank uniqueness on your data."),
                    "\n •	Note that regardless of the maximum rank value, all genes are going to be included for the analysis.",
                    "The maximum rank cut-off is to determine that genes ranking beyond the certain value would be treated as all having that same maximum rank.",
                  br(),
                  tags$img(src = "Asset 14.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
                  h3(strong("2.2 Outputs")),
                  p(strong("2.2.1 Input overview:")),
                  p("Once the input data is selected/uploaded by the user, they can readily see an overview of the studies in a table format on the main panel.",
                  "If meta-data is included, that information would also be displayed for each study."),
                  br(),
                  tags$img(src = "Asset 15.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
                  p(strong("2.2.2 Unique ranks list:")),
                  p("Upon clicking the submit button, the user is automatically guided to the “Unique ranks” tab where the results of the rank uniqueness analysis are shown.",
                    "The data table includes gene names and their unique ranks as well as effect sizes and p-values depending on the method of choice.",
                    "The uniqueness ranks and scores for any gene of interest could be searched through the search box.",
                    "The entire table can be downloaded in csv format by clicking on the “Download table!” button on top."),
                    "\n •	Note that the unique ranks are by default sorted descending for the effect size, as the hits depict the unique markers for the selected subset (right group on the contrast panel).",
                    "In case you would like to see the top unique genes of the unselected group you can sort the effect sizes ascending (by clicking on the arrows next to the column name).",
                  br(),
                  tags$img(src = "Asset 16.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
                  p(strong("2.2.3 Heatmap showing the original ranks of top unique genes:")),
                  p("The original rankings of the top unique genes can be visualized via heatmaps under the “Heatmap” tab.",
                  "The number of top unique genes for each group can be fine-tuned with the scale bars at the top.",
                  "The heatmap is by default clustered for both columns and rows (studies and genes), but users can opt out of clustering for either of the two.",
                  "Since the top unique genes are selected based on effect sizes the users need to filter genes below their desired p-value cutoff.",
                  "If meta-data are included, they’d be shown as annotation bars at the top of the heatmap.",
                  "Plots can be downloaded in desired sizes and formats (PNG, PDF, and JPEG) from the download panel at the bottom."),
                  br(),
                  tags$img(src = "Asset 17.png",
                           width = "80%",
                           style = "display: block; margin-left: auto; margin-right: auto;"),
                  br(),
           ),
           
           # Rank aggregation tutorial column
           column(4,
                  fluidRow(
                    column(12,
                           class = "scrollable-column",
                           h1(strong("3. Rank Correlation Analysis")),
                           h3(strong("3.1 Inputs")),
                           p(strong("3.1.1 Selecting datasets:")),
                           p("If the users wish to use any of the pre-loaded screening datasets as demo, they can just click on the button next to the dataset name.", 
                             "If they wish to upload and analyze their own dataset, they can select 'None' and proceed to the next section, “Uploading your own dataset”."),
                             "\n •	Please note that in case you do select a pre-loaded dataset and proceed to upload your data as well, GeneRaMeN would assume that you want to append your data to the pre-loaded one and will combine both datasets.",
                           br(),
                           tags$img(src = "Asset 2.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("3.1.2 Uploading your own dataset:")),
                           p("GeneRaMeN allows the user to upload one excel file (.xls or .xlsx) for the input ranked gene list, which can contain any number of sheets.",
                             "Each sheet then corresponds to a separate ranked gene list that you want to be included in the analysis.", 
                             "There is no limitation on the format of these gene lists as long as the first column corresponds to the “Gene names” or “Gene symbols” (Thus, Gene summary output from MAGeCK can readily be pasted into the excel sheet and used by GeneRaMeN).",
                             "Please note that this list must already be SORTED.",
                             "Since GeneRaMeN reads the first column as gene rankings it is agnostic to whether your current ranking is correctly sorted or not, therefore it is on the user to make sure all hit lists are correctly sorted.",
                             "To download an example of input file template accepted by GeneRaMeN please click",
                             a("here.", href = "https://github.com/MeisamYSF/GeneRaMeN/raw/main/SampleDataFile_GeneRaMeN.xlsx")),
                           "\n •	Please note that GeneRaMeN currently accepts Human gene lists only, since all gene lists undergo standardization to their latest HGNC official gene name.",
                           br(),
                           tags$img(src = "Asset 3.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("3.1.3 Including meta-data:")),
                           p("Additional information (e.g., cell lines, disease phenotype, etc.) can be supplemented to the studies included in the analysis.",
                             "Some meta-data such as cell lines and screening methods are already included for the pre-loaded datasets, but in case the users have opted to upload their own datasets and want to visualize heatmaps with meta-data, they must upload a meta-data file that is compatible with the uploaded dataset (same number of studies, and with same study names).",
                             "To download an example of meta-data file template acceptable by GeneRaMeN please click",
                             a("here.", href = "https://github.com/MeisamYSF/GeneRaMeN/raw/main/SampleMetaDataFile_GeneRaMeN.xlsx")),
                           "\n •	Note that this step is optional and for visualization purposes only (see “output” section in the following), thus has no impact on the analysis outcome.",
                           br(),
                           tags$img(src = "Asset 4.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("3.1.4. Rank Correlation settings and submission:")),
                           p("GeneRaMeN will calculate all the pairwise Pearson correlations of gene ranks among samples.",
                             "It is strongly recommended to put a maximum rank cut-off in the analysis to ensure all rankings have biological meanings.",
                             "However, if the user does not want to put such a threshold, they can set it to the total number of genes, keeping all the original ranks.",
                             "The default value is set to 5000. When all fields are filled press the submit button to run rank correlation on your data."),
                             "\n •	Note that regardless of the maximum rank value, all genes are going to be included for the analysis.",
                             "The maximum rank cut-off is to determine that genes ranking beyond the certain value would be treated as all having that same maximum rank.",
                           br(),
                           tags$img(src = "Asset 18.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           h3(strong("3.2 Outputs")),
                           p(strong("3.2.1 Input overview:")),
                           p("Once the input data is selected/uploaded by the user, they can readily see an overview of the studies in a table format on the main panel.",
                           "If meta-data is included, that information would also be displayed for each study."),
                           br(),
                           tags$img(src = "Asset 19.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("3.2.2. Gene correlation lists:")),
                           p("Upon clicking the submit button the user is guided to the “Correlation lists” tab where the results of the gene rank correlations are shown.",
                             "The users can select their gene of interest by clicking on it from the top left selection list.",
                             "Top positively and negatively correlated genes with the gene of interest, would be displayed on the bottom of the page, along with their corresponding correlation coefficients."),
                             "\n •	Note that genes with “NA” values are not included in the correlation analysis, hence cannot be selected from the input selector.",
                           br(),
                           tags$img(src = "Asset 20.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("3.2.3. Gene correlation line graphs:")),
                           p("To visually examine the trends in the rankings of the top correlated and anti-correlated genes with the user's gene of interest, their original ranks can be displayed in line graphs.",
                           "The gene of interest can be chosen from the top left selection list, and the number of top correlated and anti-correlated genes can be adjusted using the scale bars.",
                           "The line graph is interactive, meaning hovering the mouse cursor over each data point would provide user with more details such as the gene name, rank, and correlation coefficient with the gene of interest."),
                           br(),
                           tags$img(src = "Asset 21.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                           br(),
                           p(strong("3.2.4. Gene correlation heatmap:")),
                           p("The original ranks of the top correlated and anti-correlated genes, alongside the gene of interest, can be presented in a heatmap under the “Heatmap” tab.",
                           "This allows for a visual representation of how those genes were originally ranked in relation to the gene of interest.",
                           "The studies are clustered together which helps to identify similar studies in regard to the gene of interest correlation and anti-correlation patterns.",
                           "The number of correlated/anti-correlated genes to be included can be fine-tuned with the scale bars at the top.",
                           "If meta-data are included, they’d be shown as annotation bars at the top of the heatmap.",
                           "Plots can be downloaded in desired sizes and formats (PNG, PDF, and JPEG) from the download panel at the bottom."),
                           br(),
                           tags$img(src = "Asset 22.png",
                                    width = "80%",
                                    style = "display: block; margin-left: auto; margin-right: auto;"),
                    ),
                    
                    # vertical line
                    # column(
                    #   1,
                    #   div(class = "divider-line")
                    # ),
                  )),
         )
)